baseURL = "https://jamesacampbell.github.io/boomlabs"
languageCode = "en-us"
title = "Boom Labs"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "A port of the Grayscale theme to Hugo"

[Author]
    name = "James Campbell"
    email = "jess@boomlabs.ai"

[Social]
    twitter = "jamescampbell"
